apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: fabijanbajo-build-task
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
    - name: fabijanbajo-git
      type: git
    params:
    - name: dockerfile
      default: /workspace/fabijanbajo-git/Dockerfile
    - name: buildcontext
      default: /workspace/fabijanbajo-git
  outputs:
    resources:
    - name: fabijanbajo-image
      type: image
  steps:
  - name: build-test-push
    image: gcr.io/kaniko-project/executor:debug-v0.10.0
    env:
    - name: "DOCKER_CONFIG"
      value: "/builder/home/.docker/"
    command:
    - /kaniko/executor
    args:
    - --dockerfile=${inputs.params.dockerfile}
    - --destination=${outputs.resources.fabijanbajo-image.url}
    - --context=${inputs.params.buildcontext}
    - --target=release
