apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: fabijanbajo-image-resource
  namespace: tekton-pipelines
spec:
  type: image
  params:
  - name: url
    value: gcr.io/fabijanbajo/fabijanbajo
