apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: fabijanbajo-deploy-task
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
    - name: fabijanbajo-git
      type: git
    params:
    - name: chartpath
      default: /workspace/fabijanbajo-git/kubernetes/fabijanbajo
    - name: chartname
      default: fabijanbajo
  steps:
  - name: deploy
    image: lachlanevenson/k8s-helm:v2.14.1
    command: ["helm"]
    args:
      - upgrade
      - --install
      - ${inputs.params.chartname}
      - ${inputs.params.chartpath} 
