apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: fabijanbajo-build-task
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
    - name: fabijanbajo-git
      type: git
    params:
    - name: dockerfile
      default: /workspace/fabijanbajo-git/Dockerfile
    - name: buildcontext
      default: /workspace/fabijanbajo-git
  outputs:
    resources:
    - name: fabijanbajo-image
      type: image
  steps:
  - name: build-and-push
    image: gcr.io/makisu-project/makisu:v0.1.11
    args:
      - build
      - --push=gcr.io
      - --modifyfs=true
      - --tag=fabijanbajo/fabijanbajo:latest
      - --registry-config=/registry-config/registry.yaml
      - ${inputs.params.buildcontext}
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
    volumeMounts:
    - name: registry-config
      mountPath: /registry-config
  volumes:
  - name: registry-config
    secret:
      secretName: docker-registry-config
