apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: fabijanbajo-pipelinerun
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: fabijanbajo-pipeline
  resources:
  - name: fabijanbajo-git
    resourceRef:
      name: fabijanbajo-git-resource
  - name: fabijanbajo-image
    resourceRef:
      name: fabijanbajo-image-resource
