ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
  hosts:
  - host: devops.fabijanbajo.com
    paths:
    - /hooks/github-webhook
    - /hooks/gitlab-webhook
  tls:
  - secretName: fabijanbajo-tls-secret
    hosts:
    - devops.fabijanbajo.com

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

webhook:
  github:
    endpoint: github-webhook  
    secret: "}VY*IsCn/OX:7R@"
    branch: master
    isScriptInline: false

pipelineJob:
  enabled: true
  clone:
    cloningRepositoryUrl: <URL_FROM_WEBHOOK_PAYLOAD>
    sshSecret: ssh-secret
  build:
    buildToolImage:
      makisuSecret: docker-registry-config
    targetImage:
      host: gcr.io
      repository: fabijanbajo/fabijanbajo
      tag: <COMMIT_HASH_FROM_WEBHOOK_PAYLOAD>
  deploy:
    helmChart:
      name: fabijanbajo
      namespace: fabijanbajo
      path: kubernetes

